### ISSUE TITLE
Crash when simulated sleeping. Fine when vanilla sleeping. But not much fatigue is restoring.

### ISSUE THREAD

**Issue by Darkmega18** [Su5eD/Somnia-Awoken#46] opened 2021-05-10 03:30 UTC
**What version of Somnia Awoken are you using?**
Somnia: 1.11beta2
Forge: 14.23.5.2855

**Describe the bug**  
When I try to laydown and sleep, which should accelerate time. server crashes. clientgame is fine. 

Also as a side, when I sleep a vanilla sleep it's fine but despite sleeping at the start of the night or day when using a hammock I only get back like 15 fatigue. I did have an espresso previously, with only change to configs being to double the amount of fatigue removed.

**Is this bug related to another mod?**  
not sure. it just seems like the concurrent modification checker is... crashing with a concurrent modification error. :V but it could be just that theres too much stuff in the general area and attempting to simulate any of it is causing a massive cluster explosion of bad times. :V

**To Reproduce**  
Steps to reproduce the bug:
1. make server.
2. sleep.
3. crash.
4. ???? grofit?

**Expected behavior**  
that I should be able to lie down to simulate the world nearby and not spontaneously destroy it.

**_Crashlog_**
[crash-2021-05-09_23.12.19-server.txt](https://github.com/Su5eD/Somnia/files/6449240/crash-2021-05-09_23.12.19-server.txt)

**Comment by Su5eD** [comment] 2021-05-10 10:26
Not sure what causes the crash, since the `synchronized` block is supposed to prevent that. I can't reproduce it either, but I know of a possible fix.

> I only get back like 15 fatigue

How long have you slept?

**Comment by Darkmega18** [comment] 2021-05-10 15:57
> 
> 
> Not sure what causes the crash, since the `synchronized` block is supposed to prevent that. I can't reproduce it either, but I know of a possible fix.
> 
> > I only get back like 15 fatigue
> 
> How long have you slept?

first was like half the night atleast, from full fatigue, so I was utterly zombie walking at that point cause I was organizing storage, then the next was a full day in a hammock from comforts using vanilla mechanics straight after waking with like 80 fatigue or so right after. I think that got me far enough down to be fine. but sometimes even from full, a night of sleep would set me to 0 outright, while rarely it'll just take the difference and do like 70 total with a little left over from 90.

it might be related to the thing you fixed just earlier related to the waking up from vanilla sleep early and having 0 fatigue instantly thing.

**Comment by DrUltraLux** [comment] 2021-11-19 12:59
I was able to recreate this exact issue in 1.10.2 as well as 11.2 beta and beta2. 
First night I slept, it ran fine, crashed as soon as I woke up. 
Using a vanilla bed.

**Comment by Su5eD** [comment] 2022-06-28 11:00
Hi, I'll be closing this issue as the support for 1.12 releases is ending, with 1.16 the new LTS version. If you are able to reproduce this issue in newer versions, feel free to open a new issue and I'll look for a solution. Thanks!

**Closed as not planned by Su5eD** 2022-06-28 11:00 UTC
Labels: bug
