### ISSUE TITLE
A way to see Fatigue while sleeping

### ISSUE THREAD

**Issue by aaronhowser1** [Su5eD/Somnia-Awoken#6] opened 2020-08-08 23:04 UTC
![](https://user-images.githubusercontent.com/15698722/89721270-46435000-d9a1-11ea-88a9-d996263b264e.png)

It would be nice if you could see your current fatigue while sleeping

**Comment by Su5eD** [comment] 2020-08-09 09:05
Duplicate of #5

**Closed as completed by Su5eD** 2020-08-09 09:05 UTC
Labels: bug
