### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by EdroCode** [Su5eD/Somnia-Awoken#67] opened 2021-11-21 14:28 UTC
### Describe the bug

A image of an block or something appears when im sleeping, even if im not next to an wall, and it takes so long to the day to skip

### Is this bug related to another mod?

no

### What Version?

1.12.2

### Steps to reproduce

1. place the bed in an open area
2. click to sleep

![2021-11-21_14 27 48](https://user-images.githubusercontent.com/94792540/142765921-df51af98-56ad-43bc-9fdb-0b8a56c0c32e.png)
![2021-11-21_14 27 50](https://user-images.githubusercontent.com/94792540/142765922-592a9f36-d551-480f-9682-adaf64752c4e.png)

**Comment by Su5eD** [comment] 2021-11-21 15:02
Duplicate of #9

**Closed as completed by Su5eD** 2021-11-21 15:02 UTC
Labels: duplicate
