### ISSUE TITLE
I don't see anything

### ISSUE THREAD

**Issue by axalox** [Su5eD/Somnia-Awoken#44] opened 2021-04-25 13:12 UTC
Hello

Minecraft server 1.12.2

I've seen there is a bug with bed orientation

But with bed's pointing north, I see only leaves, but there are no leaves near my bed.
Is there something to tweak ?

If bed in another direction I only see bed.

**Comment by Su5eD** [comment] 2021-04-25 13:56
Duplicate of #9

**Closed as completed by Su5eD** 2021-04-25 13:56 UTC
Labels: bug, duplicate
