### ISSUE TITLE
Head is placed too high on the pillow, gets suffocated in wall

### ISSUE THREAD

**Issue by Darkmega18** [Su5eD/Somnia-Awoken#35] opened 2021-03-08 08:04 UTC
_Newest version: somnia:_ 1.10.2

Consider this a follow up to my last bug where I reported the concurrent modification and then changed my render settings but hadn't tested them yet at that time to fix being unable to see while sleeping.

![image](https://user-images.githubusercontent.com/8104689/110289723-f19eab00-803d-11eb-8567-8101e8d54b4d.png)
it's not a crash. but this seems like a step backwards. This was after I changed the rendering. I lie in the bed, and immediately start super dieing really fast from wall suffocation. Might want to fiddle with that to stop suffocation with beds against walls, which is usually where they get put, for decor and space reasons... :V fairly certain this wasn't the case last version either... for now I've just flipped the bed round the other way. but from the perspective it seems the player's head is placed a bit too far back on the pillow when lying down, resulting in suffocation if the block behind isn't open or not a nonsuffocateable.

**Comment by Darkmega18** [comment] 2021-03-08 15:29
and now of course it calls me a liar in my test world cause I have a bed like this, and theres no issues sleeping in it.
![image](https://user-images.githubusercontent.com/8104689/110342211-40206980-807f-11eb-9901-87ebb5ad62c5.png)
I'm so confused...

**Comment by Su5eD** [comment] 2021-03-26 07:45
Closing as "can't reproduce" for now. Let me know if you experience this again

**Closed as completed by Su5eD** 2021-03-26 07:45 UTC
Labels: bug, can't reproduce

**Comment by Darkmega18** [comment] 2021-03-26 12:40
had it several times last time I played, was pretty well constant. it's most often when I place beds too close to walls or maybe without enough head space above them? I'm gonna play a bit to test my modpack with some friends tomorrowish. I'll send the pack and you can take a look at seeing it reproduced in the pack then perhaps?

**Comment by Su5eD** [comment] 2021-03-26 21:08
Sure, but I don't think other mods would cause this issue. Somnia uses the exact same code as vanilla, so might as well be a vanilla bug

**Comment by Darkmega18** [comment] 2021-03-27 05:12
thats odd then. sometimes I seem to fall through the bed, and sometimes it tries to sleep me off center of the bed but I get shoved back to the right location of the bed (or the bug happens and I start oofing in a wall I'm not actually in) other times the head of my character ends up in an angle that isn't that of the bed's also.

I have vanilla fix and random tweaks, would any of those have any tweaks in them that could screw with it and cause it to occur in relation to the vanilla bug that you apparently fix with your config?
