### ISSUE TITLE
1.18.2 F3 doesn't show up

### ISSUE THREAD

**Issue by Swifty744** [Su5eD/Somnia-Awoken#84] opened 2022-09-08 17:09 UTC
### Describe the bug

I press F3 the cursor changes as it's supposed to but the information on the left side of the screen doesn't show up

### Is this bug related to another mod?

Not sure, quite possible like clashing but who knows

### Steps to reproduce

1. I log into the game
2. I press F3
3. F3 info screen doesn't show up at all

### Expected Behavior

For the F3 information to show up

### Additional context

This bug could be related to anything at this point but who knows, like it could be a conflict with another mod but I am certain it is this one that's causing it.

**Comment by Su5eD** [comment] 2022-09-08 18:38
What other mods are you using? Works fine for me with only Somnia installed

![f3 info](https://user-images.githubusercontent.com/51261569/189199856-f398c34a-2618-49ec-9369-27fa46e32111.png)

**Comment by Su5eD** [comment] 2022-09-28 12:39
Closing as unable to reproduce

**Closed as completed by Su5eD** 2022-09-28 12:39 UTC
Labels: bug, can't reproduce
