### ISSUE TITLE
Camera zooms in when sleeping

### ISSUE THREAD

**Issue by aaronhowser1** [Su5eD/Somnia-Awoken#14] opened 2020-08-16 07:53 UTC
**Describe the bug**
When you sleep, the camera zooms in

**Is this bug related to another mod?**
No

**To Reproduce**
Steps to reproduce the bug:
1. Set fatigue to 100
2. Sleep

**Expected behavior**
For it not to zoom in

**Screenshots**
![image](https://user-images.githubusercontent.com/15698722/90329520-301e2c80-df6b-11ea-830a-bf5e7bc8ca81.png)
![image](https://user-images.githubusercontent.com/15698722/90329576-a327a300-df6b-11ea-86fb-8066ddde0fd9.png)

**Additional context**
Still happened at low Fatigue levels, so it's not a potion thing

**Comment by Su5eD** [comment] 2020-08-16 15:11
Duplicate of #9

**Closed as completed by Su5eD** 2020-08-16 15:11 UTC
Labels: bug, duplicate
